stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}   
  paths:     
    - .m2/repository/
    - target/*.jar
    - target/*.json

build:
  image: maven:latest 
  variables:   
    MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository" 
  stage: build     
  artifacts:     
    paths:
      - target/kafka-model-schema-connector-1.0-SNAPSHOT-jar-with-dependencies.jar
      - target/config.json
      - target/consumer-config.json
  script:
    - mvn $MAVEN_CLI_OPTS -Dmaven.wagon.http.ssl.insecure=true package

deploy:
  image: docker:stable
  stage: deploy
  #services:
  #  - docker:stable-dind
  script:
      - docker build -t 'java-producer-image' -f Dockerfile.producer .
      - docker build -t 'java-consumer-image' -f Dockerfile.consumer .
      - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
      - docker push 'java-producer-image'
      - docker push 'java-consumer-image'




