stages:
  - build
  - test
  - deploy

variables:
  #TAG_PRODUCER: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:producer
  TAG_CONSUMER: $CI_REGISTRY_IMAGE/consumer:latest
  TAG_PRODUCER: $CI_REGISTRY_IMAGE/producer:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}   
  paths:     
    - .m2/repository/
    - target/*.jar
    - target/*.json

build_maven:
  image: maven:latest 
  variables:   
    MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository" 
  stage: build     
  artifacts:     
    paths:
      - target/kafka-model-schema-connector-1.0-SNAPSHOT-jar-with-dependencies.jar
      - target/config.json
      - target/consumer-config.json
  script:
    - mvn $MAVEN_CLI_OPTS -Dmaven.wagon.http.ssl.insecure=true package

build_docker:
  image: docker:stable
  stage: test
  services:
    - docker:stable-dind
  script:
      - docker build -t $TAG_PRODUCER -f Dockerfile.producer .
      - docker build -t $TAG_CONSUMER -f Dockerfile.consumer .
      - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
      - echo $TAG_LATEST
      - docker push $TAG_PRODUCER
      - docker push $TAG_CONSUMER

Deploy_producer:
  image: a6500d02.bal.au.boeing.com:5050/riskreduction/example-project/alpine:keene
  stage: deploy
  script:
    - chmod og= $ID_RSA_D01
    - ssh -i $ID_RSA_D01 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP_D01 "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - ssh -i $ID_RSA_D01 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP_D01 "docker pull $TAG_PRODUCER"
    - ssh -i $ID_RSA_D01 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP_D01 "docker container rm -f producer || true"
    - ssh -i $ID_RSA_D01 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP_D01 "docker run --rm -d --label co.elastic.logs=true --log-driver json-file --log-opt max-size=10m --name producer $TAG_PRODUCER"
     #sleep 15 then check if its up show last log
    - sleep 15
    - ssh -i $ID_RSA_D01 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP_D01 "docker ps -a | grep producer ; docker logs producer --tail 100 || true"

Deploy_consumer:
  image: a6500d02.bal.au.boeing.com:5050/riskreduction/example-project/alpine:keene
  stage: deploy
  script:
    - chmod og= $ID_RSA_D01
    - ssh -i $ID_RSA_D01 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP_D01 "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - ssh -i $ID_RSA_D01 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP_D01 "docker pull $TAG_CONSUMER"
    - ssh -i $ID_RSA_D01 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP_D01 "docker container rm -f consumer || true"
    - ssh -i $ID_RSA_D01 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP_D01 "docker run --rm -d --label co.elastic.logs=true --log-driver json-file --log-opt max-size=10m --name consumer $TAG_CONSUMER"
     #sleep 15 then check if its up show last log
    - sleep 15
    - ssh -i $ID_RSA_D01 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP_D01 "docker ps -a | grep consumer ; docker logs consumer --tail 100 || true"

    
  




