stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}   
  paths:     
    - .m2/repository/
    - target/*.jar
    - target/*.json

build:
  image: maven:latest 
  variables:   
    MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository" 
    stage: build     
    artifacts:     
      paths:
        - target/kafka-model-schema-connector-1.0-SNAPSHOT-jar-with-dependencies.jar
        - target/config.json
        - target/consumer-config.json
    script:
      #- mvn dependency:get -Dartifact=org.air6500:kafka-model-schema-java:1.0-SNAPSHOT $MAVEN_CLI_OPTS -Dmaven.wagon.http.ssl.insecure=true
      - mvn $MAVEN_CLI_OPTS -Dmaven.wagon.http.ssl.insecure=true package

deploy:
  image: a6500d02.bal.au.boeing.com:5050/riskreduction/example-project/docker
  stage:
    - deploy
  script:
      - docker build -t java-producer-image -f Dockerfile.producer .
      - docker build -t java-consumer-image -f Dockerfile.consumer .



