version: "3.3"

services:
  kafka-consumer:
    image: openjdk:14
    container_name: "com.air6500.kafka.consumer"
    #restart: always
    ports:
      - 8092:8092
    volumes:
      - "./target:/home/app:z"
      - "./logs:/logs:z"
    command: ['java', '-jar', "-Dapp.name=kafka.consumer", '/home/app/kafka-model-schema-connector-1.0-SNAPSHOT-jar-with-dependencies.jar', '--config', '/home/app/consumer-config.json']

# networks: 
#   default:
#     external: 
#       name: kafka-network